appVersion: 0.17.1
description: Distributed computation in Python with task scheduling
home: https://dask.pydata.org
icon: https://avatars3.githubusercontent.com/u/17131925?v=3&s=200
maintainers:
- email: df.rodriguez143@gmail.com
  name: danielfrg
- email: mrocklin@gmail.com
  name: mrocklin
name: dask
sources:
- https://github.com/dask/dask
version: 1.0.0

---
# nameOverride: dask
# fullnameOverride: dask

scheduler:
  name: scheduler
  image:
    repository: "daskdev/dask"
    tag: "0.17.1"
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 8786
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  image:
    repository: "daskdev/dask"
    tag: "0.17.1"
    pullPolicy: IfNotPresent
  replicas: 3
  aptPackages: >-
  default_resources:  # overwritten by resource limits if they exist
    cpu: 1
    memory: "4GiB"
  env:
    # - name: EXTRA_CONDA_PACKAGES
    #   value: numba xarray -c conda-forge
    # - name: EXTRA_PIP_PACKAGES
    #   value: s3fs dask-ml --upgrade
  resources: {}
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 1
      memory: 1G

jupyter:
  name: jupyter
  enabled: false
