apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ngshare-standalone-pvc
  namespace: jhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
  volumeMode: Filesystem
