ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM $BASE_CONTAINER

# Install any additional system packages
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends vim curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID

# Install some packages into base, create GPU enabled tensorflow conda
# environment, and clean
ARG ENVIRONMENT_FILE=environment-tf.yml
ADD $ENVIRONMENT_FILE /tmp/environment.yml
RUN mamba install --quiet --yes \
      'conda-forge::nb_conda_kernels' \
      'conda-forge::jupyterlab-git' \
      'conda-forge::ipywidgets' && \
    mamba env update -f /tmp/environment.yml && \
    pip install --no-cache-dir nbgitpuller && \
    mamba clean --all -f -y && \
    jupyter lab clean -y && \
    npm cache clean --force && \
    rm -rf /home/$NB_USER/.cache/yarn && \
    rm -rf /home/$NB_USER/.node-gyp && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

USER ${NB_UID}
