apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-memory-deployment
  labels:
    app: high-memory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: high-memory-app
  template:
    metadata:
      labels:
        app: high-memory-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1"
