# deploymentPatch.yml referenced in deploymentPatch.sh
---
spec:
  template:
    spec:
      nodeSelector:
        #"node-role.kubernetes.io/master": ""
        "node-role.kubernetes.io/control-plane": ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
