apiVersion: v1
kind: Pod
metadata:
  name: singularity
  namespace: default
spec:
  containers:
  - name: singularity
    image: quay.io/singularity/singularity:v3.11.0
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: true
       allowPrivilegeEscalation: true
