export RESTIC_REPOSITORY_FILE="./RESTIC_REPOSITORY"
export RESTIC_PASSWORD_FILE='./RESTIC_PASSWORD'
export AWS_ACCESS_KEY_ID=$(cat ./AWS_ACCESS_KEY_ID)
export AWS_SECRET_ACCESS_KEY=$(cat ./AWS_SECRET_ACCESS_KEY)

