apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-cache-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-folder-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  selector:
    role: nfs
  # NFS volume does not support DNS, so choosing a IP
  # for Magnum
  # clusterIP: 10.254.77.77
  # for Kubespray
  clusterIP: 10.233.46.63
  ports:
    # Open the ports required by the NFS server
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
    - name: tcp-111
      port: 111
      protocol: TCP
    - name: tcp-32803
      port: 32803
      protocol: TCP
    - name: udp-32769
      port: 32769
      protocol: UDP
    - name: udp-892
      port: 892
      protocol: UDP
    - name: tcp-892
      port: 892
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-ssh-service
spec:
  selector:
    role: nfs
  type: NodePort
  ports:
    - nodePort: 30022
      port: 20022
      targetPort: 22
      protocol: TCP
