apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 500Gi
