apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-cephfs
  namespace: jhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: manila-cephfs-pv
